First commit
i-Gor3040/exam pull request #1
Opened 2024-03-24 18:42 UTC by i-Gor3040

2024-03-25 21:01 UTC, DmytroSanitarskyi requested changes
1. всі cy.wait з явно вказаними мілісекундами треба видалити (для банера залишив підказку)
2. Позалишав коменти в тестах, вони відносяться до всього проекту, не став їх дублювати
3. Для реєстрації додайте негативні тести для перевірки еррор месседжів
4. node_modules треба видалити, додати в гіт ігнор і після цього запушити)

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/support/pages/BasePage.js
> +  dismissWelcomeBanner() {
dismissWelcomeBanner() {
        cy.get('[aria-label="Close Welcome Banner"]', {timeout: 15000}).click();
    }

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/e2e/authorization.cy.js
> +describe('Authorization positive scenarios', () => {
перед цим тестом треба реєструвати юзера. Можна через UI зробити, оскільки кроки у вас вже є, можна спробувати запитом. Запит на реєстрацію буде більш правильним в цьому випадку, але з ним потрібно розбиратися і реалізовувати з нуля

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/e2e/authorization.cy.js
> +import LoginPage from "../support/pages/LoginPage";
імпорти для сторінок треба називати з маленької літери

`import loginPage from "../support/pages/LoginPage";`

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/e2e/authorization.cy.js
> +describe('Authorization positive scenarios', () => {
Коли додасте реєстрацію, то тест буде проходити завжди

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/e2e/feedback.cy.js
> +            FeedbackPage.getResultField().type(result); // I have troubles with passing result outside. What is the best practice here?
тут все правильно зроблено, виносити цей крок за межі функції не потрібно

2024-03-25 21:01 UTC, DmytroSanitarskyi commented on cypress/e2e/order.cy.js
> +        cy.wait(1000);
використайте intercept для цього тесту замість таких вейтів

2024-03-25 21:03 UTC, DmytroSanitarskyi requested changes

2024-03-25 21:03 UTC, DmytroSanitarskyi commented on cypress/support/pages/BasketPage.js
> +        return cy.get('button').contains(' Checkout ');
cy.contains('button', ' Checkout ');

2024-04-03 20:21 UTC, i-Gor3040 commented on cypress/support/pages/BasePage.js
> +  dismissWelcomeBanner() {
Thanks! I thought the banner appears randomly.

2024-04-03 20:23 UTC, i-Gor3040 commented on cypress/e2e/authorization.cy.js
> +describe('Authorization positive scenarios', () => {
👍

2024-04-03 20:51 UTC, i-Gor3040 commented on cypress/e2e/authorization.cy.js
> +import LoginPage from "../support/pages/LoginPage";
👍

2024-04-03 20:51 UTC, i-Gor3040 commented on cypress/e2e/feedback.cy.js
> +            FeedbackPage.getResultField().type(result); // I have troubles with passing result outside. What is the best practice here?
👍

2024-04-03 20:54 UTC, i-Gor3040 commented on cypress/support/pages/BasketPage.js
> +        return cy.get('button').contains(' Checkout ');
👍

2024-04-04 08:27 UTC, closed without merging